// Copyright (c) 2018 The VeChainThor developers
// Distributed under the GNU Lesser General Public License v3.0 software license, see the accompanying
// file LICENSE or <https://www.gnu.org/licenses/lgpl-3.0.html>

// Package eip6780 tests EIP-6780: SELFDESTRUCT only in same transaction.
//
// EIP-6780 (Cancun / VeChain INTERSTELLAR fork) restricts SELFDESTRUCT:
//   - Pre-existing contract: only the balance is transferred; code and storage persist.
//   - Contract created in the same transaction: full deletion (code + storage removed).
//
// Contracts under test (see contracts/):
//   - Destructible.sol — exposes a destroy(recipient) function that calls SELFDESTRUCT.
//   - Factory.sol      — deploys a Destructible child and calls destroy on it in one tx,
//     exercising the same-transaction deletion path.
//
// To recompile contracts:
//
//	cd contracts && go generate
package eip6780

import (
	"math/big"
	"testing"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vechain/thor/v2/api"
	"github.com/vechain/thor/v2/thor"
	"github.com/vechain/thor/v2/thorclient"
	"github.com/vechain/thor/v2/tx"

	"github.com/vechain/interstellar-e2e/tests/eip6780/contracts/generated/destructible"
	"github.com/vechain/interstellar-e2e/tests/eip6780/contracts/generated/factory"
	"github.com/vechain/interstellar-e2e/tests/helper"
)

// ---------------------------------------------------------------------------
// Compiled contract bytecode (generated by contracts/gen.go)
// Recompile with: cd tests/eip6780/contracts && go generate
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Test 1: Pre-fork — SELFDESTRUCT opcode is valid (does not revert)
// ---------------------------------------------------------------------------

// TestEIP6780_PreFork_SelfDestructOpcodeValid verifies that the SELFDESTRUCT
// opcode (0xff) was already valid before the INTERSTELLAR fork. Deploying
// Destructible and calling destroy() at pre-fork revision must not revert.
// This establishes the baseline: the opcode exists; the fork only changes its semantics.
func TestEIP6780_PreFork_SelfDestructOpcodeValid(t *testing.T) {
	client := helper.NewClient(nodeURL)

	callData := &api.BatchCallData{
		Clauses: api.Clauses{
			// Clause 0: deploy Destructible
			{Data: destructible.Bytecode.Hex()},
		},
		Gas: 300_000,
	}

	results, err := client.InspectClauses(callData, thorclient.Revision(helper.PreForkRevision))
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.False(t, results[0].Reverted,
		"pre-fork: Destructible deployment must not revert (vmError: %s)", results[0].VMError)
}

// ---------------------------------------------------------------------------
// Test 2: Post-fork — SELFDESTRUCT on a pre-existing contract does NOT delete it
// ---------------------------------------------------------------------------

// TestEIP6780_PostFork_PreExistingContractNotDeleted deploys a Destructible
// contract, waits for it to be mined (making it a pre-existing contract), then
// calls destroy() in a separate transaction.
//
// Per EIP-6780: only the balance is transferred; the contract code and storage
// must survive because SELFDESTRUCT was not called in the same tx as creation.
func TestEIP6780_PostFork_PreExistingContractNotDeleted(t *testing.T) {
	client := helper.NewClient(nodeURL)

	// Step 1: Deploy Destructible (Tx 1 — establishes it as a pre-existing contract).
	deployTx := helper.BuildTx(t, client, 300_000, tx.NewClause(nil).WithData(destructible.Bytecode.Bytes()))
	deployResult, err := client.SendTransaction(deployTx)
	require.NoError(t, err, "deploy tx must be accepted by the node")

	deployReceipt := helper.WaitForReceipt(t, client, deployResult.ID, 30*time.Second)
	require.False(t, deployReceipt.Reverted, "Destructible deploy must not revert")
	require.Len(t, deployReceipt.Outputs, 1)
	require.NotNil(t, deployReceipt.Outputs[0].ContractAddress, "deploy must produce a contract address")

	contractAddr := *deployReceipt.Outputs[0].ContractAddress

	// Confirm the contract has code immediately after deployment.
	// We use the default "best" revision here — not PostForkRevision (block 1) —
	// because the deploy tx may be mined in a later block; block 1 wouldn't have
	// the contract in state yet.
	acctAfterDeploy, err := client.Account(&contractAddr)
	require.NoError(t, err)
	require.True(t, acctAfterDeploy.HasCode, "Destructible must have code after deployment")

	// Step 2: Call destroy(address(0)) on the pre-existing contract (Tx 2).
	callTx := helper.BuildTx(t, client, 100_000,
		tx.NewClause(&contractAddr).WithData(destructible.Methods().DestroyMethod().MustPack(common.Big0).Bytes()),
	)
	callResult, err := client.SendTransaction(callTx)
	require.NoError(t, err, "destroy() call tx must be accepted")

	callReceipt := helper.WaitForReceipt(t, client, callResult.ID, 30*time.Second)
	require.False(t, callReceipt.Reverted,
		"destroy() must not revert — EIP-6780 still executes SELFDESTRUCT, only deletion is restricted")

	// Step 3: Contract must still have code (EIP-6780 protection for pre-existing contracts).
	acctAfterDestroy, err := client.Account(&contractAddr)
	require.NoError(t, err)
	assert.True(t, acctAfterDestroy.HasCode,
		"post-fork: pre-existing contract must retain its code after SELFDESTRUCT (EIP-6780)")
}

// ---------------------------------------------------------------------------
// Test 3: Post-fork — contract created and self-destructed in the same tx IS deleted
// ---------------------------------------------------------------------------

// TestEIP6780_PostFork_SameTxCreationIsDeleted deploys the Factory contract,
// then calls deployAndDestroy() which — in a single transaction:
//  1. Creates a new Destructible child via CREATE.
//  2. Calls destroy(msg.sender) on the child.
//
// Since the child was created in the same transaction as the SELFDESTRUCT call,
// EIP-6780 allows full deletion. After the tx, the child must have no code.
func TestEIP6780_PostFork_SameTxCreationIsDeleted(t *testing.T) {
	client := helper.NewClient(nodeURL)

	// Step 1: Deploy the Factory (Tx 1).
	deployTx := helper.BuildTx(t, client, 500_000, tx.NewClause(nil).WithData(factory.Bytecode.Bytes()))
	deployResult, err := client.SendTransaction(deployTx)
	require.NoError(t, err, "Factory deploy tx must be accepted")

	deployReceipt := helper.WaitForReceipt(t, client, deployResult.ID, 30*time.Second)
	require.False(t, deployReceipt.Reverted, "Factory deploy must not revert")
	require.Len(t, deployReceipt.Outputs, 1)
	require.NotNil(t, deployReceipt.Outputs[0].ContractAddress)

	factoryAddr := *deployReceipt.Outputs[0].ContractAddress

	// Step 2: Call deployAndDestroy() — child is created AND destroyed in one tx (Tx 2).
	callTx := helper.BuildTx(t, client, 500_000,
		tx.NewClause(&factoryAddr).WithData(factory.Methods().DeployAndDestroyMethod().MustPack().Bytes()),
	)
	callResult, err := client.SendTransaction(callTx)
	require.NoError(t, err, "deployAndDestroy() call tx must be accepted")

	callReceipt := helper.WaitForReceipt(t, client, callResult.ID, 30*time.Second)
	require.False(t, callReceipt.Reverted, "deployAndDestroy() must not revert")

	// The child contract address is deterministic: it was the first contract
	// created inside clause 0 of callTx (creation counter = 1; the factory
	// call itself is not a creation, the child CREATE inside it is counter 1).
	childAddr := thor.CreateContractAddress(*callResult.ID, 0, 1)

	// Step 3: Child must have no code — same-tx creation allows full EIP-6780 deletion.
	childAcct, err := client.Account(&childAddr)
	require.NoError(t, err)
	assert.False(t, childAcct.HasCode,
		"post-fork: child created and self-destructed in the same tx must have no code (EIP-6780 same-tx exception)")
}

// ---------------------------------------------------------------------------
// Test 4: Post-fork — SELFDESTRUCT to self on a pre-existing contract is a no-op
// ---------------------------------------------------------------------------

// TestEIP6780_PostFork_SelfDestructToSelfIsNoop deploys a Destructible contract,
// funds it with 1 VET, then calls destroy(contractAddress) — passing the contract's
// own address as the recipient.
//
// Per EIP-6780, on a pre-existing contract:
//   - The contract must not be deleted (code persists).
//   - The balance must not change (self-transfer is a no-op).
func TestEIP6780_PostFork_SelfDestructToSelfIsNoop(t *testing.T) {
	client := helper.NewClient(nodeURL)

	// Step 1: Deploy Destructible (Tx 1).
	deployTx := helper.BuildTx(t, client, 300_000, tx.NewClause(nil).WithData(destructible.Bytecode.Bytes()))
	deployResult, err := client.SendTransaction(deployTx)
	require.NoError(t, err)

	deployReceipt := helper.WaitForReceipt(t, client, deployResult.ID, 30*time.Second)
	require.False(t, deployReceipt.Reverted, "Destructible deploy must not revert")
	require.Len(t, deployReceipt.Outputs, 1)
	require.NotNil(t, deployReceipt.Outputs[0].ContractAddress)

	contractAddr := *deployReceipt.Outputs[0].ContractAddress

	// Step 2: Fund the contract with 1 VET so we can assert balance stability (Tx 2).
	// Use 50_000 gas — 21_000 (the base clause cost) is not enough because calling
	// receive() has additional EVM execution cost (~21055 used in practice).
	fundTx := helper.BuildTx(t, client, 50_000,
		tx.NewClause(&contractAddr).WithValue(big.NewInt(1e18)),
	)
	fundResult, err := client.SendTransaction(fundTx)
	require.NoError(t, err)
	fundReceipt := helper.WaitForReceipt(t, client, fundResult.ID, 30*time.Second)
	require.False(t, fundReceipt.Reverted, "funding transfer must not revert")

	balanceBefore, err := client.Account(&contractAddr)
	require.NoError(t, err)

	// Step 3: Call destroy(contractAddr) — self as recipient (Tx 3).
	// ABI encode destroy(address) with the contract's own address as argument.
	addrPadded := make([]byte, 32)
	copy(addrPadded[12:], contractAddr.Bytes())
	selfDestroyCalldata := append([]byte{0x00, 0xf5, 0x5d, 0x9d}, addrPadded...)

	callTx := helper.BuildTx(t, client, 100_000,
		tx.NewClause(&contractAddr).WithData(selfDestroyCalldata),
	)
	callResult, err := client.SendTransaction(callTx)
	require.NoError(t, err)

	callReceipt := helper.WaitForReceipt(t, client, callResult.ID, 30*time.Second)
	require.False(t, callReceipt.Reverted,
		"destroy(self) must not revert — EIP-6780 executes SELFDESTRUCT but restricts deletion")

	// Step 4: Assert the contract still has code and balance is unchanged.
	acctAfter, err := client.Account(&contractAddr)
	require.NoError(t, err)

	assert.True(t, acctAfter.HasCode,
		"post-fork: pre-existing contract calling SELFDESTRUCT to self must retain its code (EIP-6780 no-op)")
	assert.Equal(t, balanceBefore.Balance, acctAfter.Balance,
		"post-fork: SELFDESTRUCT to self must not change the contract balance (EIP-6780 no-op)")
}
