package eip7939

// EIP-7939 (CLZ) adds opcode 0x1e for counting leading zero bits in a 256-bit word,
// active at the INTERSTELLAR fork.
//
// The bytecode generated by clzBytecode:
//  1. PUSH32 <input>   — push the 256-bit value under test
//  2. CLZ (0x1e)       — replace it with the number of leading zero bits (0–256)
//  3. MSTORE at offset 0
//  4. RETURN 32 bytes from offset 0
//
// Pre-fork: 0x1e is an invalid opcode; the EVM reverts.

import (
	"encoding/hex"
	"math/big"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/vechain/thor/v2/api"
	"github.com/vechain/thor/v2/thorclient"

	"github.com/vechain/interstellar-e2e/tests/helper"
)

// clzBytecode builds init-code that pushes a 32-byte value, executes CLZ, and
// returns the result. Running via InspectClauses (To=nil) simulates contract
// creation so RETURN data appears in CallResult.Data.
func clzBytecode(input [32]byte) []byte {
	code := make([]byte, 0, 42)
	code = append(code, 0x7f)        // PUSH32
	code = append(code, input[:]...) // <32-byte value>
	code = append(code, 0x1e)        // CLZ
	code = append(code, 0x60, 0x00)  // PUSH1 0x00  (MSTORE offset)
	code = append(code, 0x52)        // MSTORE
	code = append(code, 0x60, 0x20)  // PUSH1 0x20  (RETURN size)
	code = append(code, 0x60, 0x00)  // PUSH1 0x00  (RETURN offset)
	code = append(code, 0xf3)        // RETURN
	return code
}

func TestCLZ_PreFork(t *testing.T) {
	client := helper.NewClient(nodeURL)

	var input [32]byte
	input[31] = 0x01 // arbitrary non-zero value

	callData := &api.BatchCallData{
		Clauses: api.Clauses{
			{Data: "0x" + hex.EncodeToString(clzBytecode(input))},
		},
		Gas: 100_000,
	}

	// 0x1e is not in the pre-Osaka instruction set; the EVM treats it as an
	// invalid opcode and halts with a revert.
	results, err := client.InspectClauses(callData, thorclient.Revision(helper.PreForkRevision))
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.True(t, results[0].Reverted,
		"CLZ must revert before INTERSTELLAR (invalid opcode)")
}

func TestCLZ_PostFork(t *testing.T) {
	client := helper.NewClient(nodeURL)

	tests := []struct {
		name     string
		input    string
		expected uint64
	}{
		{"zero", "0000000000000000000000000000000000000000000000000000000000000000", 256},
		{"one", "0000000000000000000000000000000000000000000000000000000000000001", 255},
		{"11_bits", "00000000000000000000000000000000000000000000000000000000000006ff", 245},
		{"40_bits", "000000000000000000000000000000000000000000000000000000ffffffffff", 216},
		{"second_highest_bit", "4000000000000000000000000000000000000000000000000000000000000000", 1},
		{"all_but_msb", "7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", 1},
		{"msb_set", "8000000000000000000000000000000000000000000000000000000000000000", 0},
		{"all_ones", "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", 0},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			var input [32]byte
			copy(input[:], common.FromHex(tc.input))

			callData := &api.BatchCallData{
				Clauses: api.Clauses{
					{Data: "0x" + hex.EncodeToString(clzBytecode(input))},
				},
				Gas: 100_000,
			}

			results, err := client.InspectClauses(callData, thorclient.Revision(helper.PostForkRevision))
			require.NoError(t, err)
			require.Len(t, results, 1)
			assert.False(t, results[0].Reverted,
				"CLZ must not revert after INTERSTELLAR (vmError: %s)", results[0].VMError)

			got := new(big.Int).SetBytes(common.FromHex(results[0].Data))
			assert.Equal(t, tc.expected, got.Uint64(),
				"clz(0x%s) = %d; want %d", tc.input, got.Uint64(), tc.expected)
		})
	}
}
