name: Lint

on:
  push:

permissions:
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v7
        with:
          go-version: '1.26.5'
          cache: false

      - name: Lint network
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.11.3
          working-directory: network
          args: --timeout=10m --config=../.golangci.yml
          skip-cache: true

      - name: Lint tests
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.11.3
          working-directory: tests
          args: --timeout=10m --config=../.golangci.yml
          skip-cache: true
